export const cardData=[
    {
        id:1,
        img:'assets/furniture-full-stack.png',
        name:'Elite Online Furniture Website',
        category:'MERN Stack Application',
        btn1:'Demo',
        btn2:'Source Code',
        demolink:'https://online-furniture-frontend.vercel.app/',
        codelink:'https://github.com/akhi1817/Online-furniture-frontend',
    },
    {
        id:2,
        img:'assets/shopping-frontend.png',
        name:'Shopping Website',
        category:'React Application',
        btn1:'Demo',
        btn2:'Source Code',
        demolink:'https://shopping-website-frontend-pink.vercel.app/',
        codelink:'https://github.com/akhi1817/Shopping-website',
    },
    {
        id:3,
        img:'assets/restaurant-frontend.png',
        name:'One8 Restaurant Website',
        category:'React Application',
        btn1:'Demo',
        btn2:'Source Code',
        demolink:'https://one8-restaurent-app.vercel.app/',
        codelink:'https://github.com/akhi1817/one8-restaurent-app',
    },
]